name = "h"
main  = "./output/worker.js"
cron= [0 0 * * mon,wed,fri,sun]
[[kv_namespaces]]
binding = "hhz"
id = "00d01617e3f54508886db4143435168d"
[[d1_databases]]
binding = "DB" # available in your Worker on env.DB
database_name = "h"
database_id = "e7f10800-8ed7-4c0a-8a04-d2e8b4d9756a"
compatibility_date = "2024-10-02"